language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t danielwong0323/docker-react -f Dockerfile.dev .

script:
  - dokcer run -e CI=true danielwong0323/docker-react npm run test